ROOT:
  path: '/'

VERIFY:
  path: '/verify'

VERIFY_EMAIL_ROOT:
  path: '/confirm'

CONFIRM:
  path: '/confirm'

VERIFY_EMAIL_SENDED:
  path: '/confirm/email/sended'

VERIFY_EMAIL_PENDING:
  path: '/confirm/email/verify/:key'

VERIFY_EMAIL_VERIFIED:
  path: '/confirm/email/verified'

VERIFY_EMAIL_DECLINED:
  path: '/confirm/email/declined'

ACCOUNT:
  path: '/account'
