ROOT:
  path: '/'

# user verification
VERIFY:
  path: '/verify'

VERIFY_TERMS:
  path: '/verify/terms'

VERIFY_USER_INFO:
  path: '/verify/user-info'

VERIFY_DOCUMENT:
  path: '/verify/document'

VERIFY_LOADER:
  path: '/verify/loader'

ACCOUNT:
  path: '/account'

CONFIRM:
  path: '/confirm'

# old stuff
VERIFY_EMAIL_ROOT:
  path: '/confirm'

VERIFY_EMAIL_SENDED:
  path: '/confirm/email/sended'

VERIFY_EMAIL_PENDING:
  path: '/confirm/email/verify/:key'

VERIFY_EMAIL_VERIFIED:
  path: '/confirm/email/verified'

VERIFY_EMAIL_DECLINED:
  path: '/confirm/email/declined'

CONFIRM_ADDRESS_CHANGE:
  path: '/confirm/address-change/request/:operationId/:token'

CONFIRM_ADDRESS_CHANGE_SUCCESS:
  path: '/confirm/address-change/success'

CONFIRM_ADDRESS_CHANGE_FAIL:
  path: '/confirm/address-change/fail'

CONFIRM_PASSWORD_CHANGE:
  path: '/confirm/password-change/request/:uid/:token'

CONFIRM_WITHDRAW:
  path: '/confirm/withdraw/request/:operationId/:token'

CONFIRM_WITHDRAW_SUCCESS:
  path: '/confirm/withdraw/success'

CONFIRM_WITHDRAW_FAIL:
  path: '/confirm/withdraw/fail'
